export const FETCH_PRODUCTS ="FETCH_PRODUCT";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const UPDADE_PRODUCT ="UPDATE_PRODUCT";
export const DELETE_PRODUCT ="DELETE_PRODUCT";
export const EDIT_PRODUCT = "EDIT_PRODUCT";